# This config file for Travis CI utilizes https://github.com/ros-planning/moveit_ci/ package.
sudo: required
dist: xenial
services:
  - docker
language: cpp
cache: ccache
compiler: gcc

notifications:
  email:
    recipients:
env:
  global:
    - ROS_DISTRO=melodic
    - UPSTREAM_WORKSPACE=https://raw.githubusercontent.com/ros-planning/moveit/$ROS_DISTRO-devel/moveit.rosinstall
  matrix:
    - DOCKER_IMAGE=moveit/moveit:master-source   TEST=clang-format,catkin_lint
    - DOCKER_IMAGE=moveit/moveit:master-source

before_script:
  - git clone -q --depth=1 https://github.com/ros-planning/moveit_ci.git .moveit_ci
script:
  - .moveit_ci/travis.sh