# This config file for Travis CI utilizes https://github.com/ros-planning/moveit_ci package.
sudo: required
dist: xenial
services:
  - docker
language: cpp
compiler: gcc
cache: ccache

notifications:
  email:
    recipients:

env:
  global:
    - ROS_DISTRO=melodic
  matrix:
    - TEST=clang-format,catkin_lint
      UPSTREAM_WORKSPACE=.rosinstall/random_pick/random_pick.rosinstall

    - DOCKER_IMAGE=xiaotaoqi/moveit_example_apps:random_pick
      BEFORE_SCRIPT="source moveit_example_apps/.travis/random_pick/before_script.sh"
      UPSTREAM_WORKSPACE=.rosinstall/random_pick/random_pick.rosinstall

before_script:
  - git clone -q --depth=1 https://github.com/ros-planning/moveit_ci.git .moveit_ci
script:
  - .moveit_ci/travis.sh
