# This config file for Travis CI utilizes https://github.com/ros-planning/moveit_ci package.
sudo: required
dist: xenial
services:
  - docker
language: cpp
compiler: gcc
cache: ccache

notifications:
  email:
    recipients:

env:
  global:
    - ROS_DISTRO=melodic
    - UPSTREAM_WORKSPACE=.rosinstall/random_pick/random_pick.rosinstall
  matrix:
    - TEST=clang-format,catkin_lint
    - DOCKER_IMAGE=moveit/moveit:master-source   BEFORE_SCRIPT="source moveit_example_apps/.travis/random_pick/before_script.sh" 

before_script:
  - git clone -q --depth=1 https://github.com/ros-planning/moveit_ci.git .moveit_ci
script:
  - .moveit_ci/travis.sh
